repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: debug-statements
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/pycqa/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter
        args: [
          --wrap-summaries=100,
          --wrap-descriptions=0,
          --in-place,
          --blank
        ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8-broken-line"
          - "flake8-quotes"
          - "flake8-docstrings"
          - "flake8-pytest-style"
          - "flake8-pyproject"

  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.19.1
    hooks:
      - id: gitlint
      - id: gitlint-ci
        args: [-c, ignore-by-title.regex=None, --commits, origin/develop..]

  - repo: local
    hooks:
        # Linters below require full python environment to run
      - id: local-linters
        name: local linters
        entry: inv linters.all
        language: system
        pass_filenames: false
        types: [ python ]
